---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: free5gc/ausf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: sbi
          volumeMounts:
            - name: ausf-config
              mountPath: /free5gc/config/ausf.yaml
              subPath: ausf.yaml
      volumes:
        - name: ausf-config
          configMap:
            name: ausf-config
---
apiVersion: v1
kind: Service
metadata:
  name: ausf
spec:
  selector:
    app: ausf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
