---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
data:
  upf.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    configuration:
      gtpu:
        ifList:
          - upfgtp
      pfcp:
        addr: upf
      dnnList:
        - dnn: "internet"
          cidr: "10.60.0.0/16"
