---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: free5gc/amf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: sbi
          volumeMounts:
            - name: amf-config
              mountPath: /free5gc/config/amf.yaml
              subPath: amf.yaml
      volumes:
        - name: amf-config
          configMap:
            name: amf-config
---
apiVersion: v1
kind: Service
metadata:
  name: amf
spec:
  selector:
    app: amf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
