---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
data:
  nrf.yaml: |
    info:
      version: 1.0.0
      description: NRF configuration
    configuration:
      sbi:
        addr: nrf
        port: 8000
      defaultPlmnId:
        mcc: "001"
        mnc: "01"
