---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf
          image: free5gc/nrf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: sbi
          volumeMounts:
            - name: nrf-config
              mountPath: /free5gc/config/nrf.yaml
              subPath: nrf.yaml
      volumes:
        - name: nrf-config
          configMap:
            name: nrf-config
---
apiVersion: v1
kind: Service
metadata:
  name: nrf
spec:
  selector:
    app: nrf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
