---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  labels:
    app: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: free5gc/smf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: sbi
          volumeMounts:
            - name: smf-config
              mountPath: /free5gc/config/smf.yaml
              subPath: smf.yaml
      volumes:
        - name: smf-config
          configMap:
            name: smf-config
---
apiVersion: v1
kind: Service
metadata:
  name: smf
spec:
  selector:
    app: smf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
