---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
data:
  udm.yaml: |
    info:
      version: 1.0.0
      description: UDM configuration
    configuration:
      sbi:
        addr: udm
        port: 8000
      nrfUri: http://nrf:8000
