---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      containers:
        - name: udm
          image: free5gc/udm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: sbi
          volumeMounts:
            - name: udm-config
              mountPath: /free5gc/config/udm.yaml
              subPath: udm.yaml
      volumes:
        - name: udm-config
          configMap:
            name: udm-config
---
apiVersion: v1
kind: Service
metadata:
  name: udm
spec:
  selector:
    app: udm
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
